-- ClipClash database setup for Supabase
-- Run this entire file once in: Supabase Dashboard -> SQL Editor -> New query

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null check (username ~ '^[A-Za-z0-9_]{3,20}$'),
  display_name text not null check (char_length(display_name) between 1 and 30),
  bio text not null default '' check (char_length(bio) <= 140),
  created_at timestamptz not null default now()
);

create unique index if not exists profiles_username_lower_idx on public.profiles (lower(username));

create table if not exists public.clips (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 70),
  game text not null check (game in ('Fortnite','Roblox','Minecraft','Valorant','GTA V','Rocket League','Other')),
  clip_url text not null check (char_length(clip_url) <= 500 and clip_url ~* '^https://'),
  created_at timestamptz not null default now()
);

create table if not exists public.likes (
  clip_id bigint not null references public.clips(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (clip_id, user_id)
);

create index if not exists clips_created_at_idx on public.clips (created_at desc);
create index if not exists clips_game_idx on public.clips (game);
create index if not exists likes_clip_id_idx on public.likes (clip_id);

-- Create the public profile automatically from safe signup metadata.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  desired_username text;
  desired_name text;
begin
  desired_username := coalesce(new.raw_user_meta_data ->> 'username', 'player_' || substr(new.id::text, 1, 8));
  desired_name := coalesce(new.raw_user_meta_data ->> 'display_name', desired_username);

  if desired_username !~ '^[A-Za-z0-9_]{3,20}$' then
    desired_username := 'player_' || substr(new.id::text, 1, 8);
  end if;

  insert into public.profiles (id, username, display_name)
  values (new.id, desired_username, left(desired_name, 30));
  return new;
end;
$$;

-- Recreate the trigger safely.
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- RLS: profiles/clips/likes are public-readable, but only signed-in owners can write their own rows.
alter table public.profiles enable row level security;
alter table public.clips enable row level security;
alter table public.likes enable row level security;

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.clips from anon, authenticated;
revoke all on table public.likes from anon, authenticated;

grant select on table public.profiles to anon, authenticated;
grant update on table public.profiles to authenticated;
grant select on table public.clips to anon, authenticated;
grant insert, update, delete on table public.clips to authenticated;
grant select on table public.likes to anon, authenticated;
grant insert, delete on table public.likes to authenticated;
grant usage, select on sequence public.clips_id_seq to authenticated;

drop policy if exists "Profiles are public" on public.profiles;
create policy "Profiles are public" on public.profiles for select to anon, authenticated using (true);

drop policy if exists "Users update own profile" on public.profiles;
create policy "Users update own profile" on public.profiles for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists "Clips are public" on public.clips;
create policy "Clips are public" on public.clips for select to anon, authenticated using (true);

drop policy if exists "Users insert own clips" on public.clips;
create policy "Users insert own clips" on public.clips for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users update own clips" on public.clips;
create policy "Users update own clips" on public.clips for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users delete own clips" on public.clips;
create policy "Users delete own clips" on public.clips for delete to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Likes are public" on public.likes;
create policy "Likes are public" on public.likes for select to anon, authenticated using (true);

drop policy if exists "Users like as themselves" on public.likes;
create policy "Users like as themselves" on public.likes for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users remove own likes" on public.likes;
create policy "Users remove own likes" on public.likes for delete to authenticated
using ((select auth.uid()) = user_id);
